default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: my_academy_quest_003_development
  username: aueaarri
  password: jm131038                
  host: 127.0.0.1
  port: 5432

  

test:
  <<: *default
  database: my_academy_quest_003_test


production:
  primary: &primary_production
    <<: *default
    database: my_academy_quest_003_production
    username: my_academy_quest_003
    password: <%= ENV["MY_ACADEMY_QUEST_003_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: my_academy_quest_003_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_academy_quest_003_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_academy_quest_003_production_cable
    migrations_paths: db/cable_migrate