default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: my_academy_quest_003_development
  username: aueaarri
  password: jm131038                
  host: 127.0.0.1
  port: 5432

  

test:
  <<: *default
  database: my_academy_quest_003_test


production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  variables:
    sslmode: require
